test_that("brak p nie jest traktowany jako nieistotny wynik", {
  x <- stats::t.test(1:7, c(3, 4, 2, 7, 8, 10, 5))
  x$p.value <- NA_real_
  expect_match(wniosek_ind(x), "brak warto")
  expect_error(wniosek_ind(x, alpha = 2), "alpha")
  expect_match(badaniaZI:::format_liczba_apa(c(2, 3)), "2.00", fixed = TRUE)
})

test_that("Spearman nie otrzymuje fikcyjnych stopni swobody", {
  x <- stats::cor.test(1:8, c(1, 3, 2, 5, 4, 7, 8, 6), method = "spearman")
  expect_false(grepl("(NA)", wniosek_cor(x), fixed = TRUE))
  expect_match(wniosek_cor(x), "rho", fixed = TRUE)
  p <- stats::cor.test(1:8, c(1, 3, 2, 5, 4, 7, 8, 6))
  expect_match(wniosek_cor(p), "95% CI", fixed = TRUE)
  expect_match(wniosek_reg(stats::lm(mpg ~ 1, data = mtcars)), "tylko wyraz wolny")
})

test_that("testy t opisują właściwy parametr i zachowują poziom CI", {
  x <- c(2, 3, 5, 6, 8, NA)
  y <- c(4, 6, 8, 9, 9, 12)
  jedna <- wniosek_one_sample(t.test(x, mu = 3, conf.level = .9), alpha = .01)
  expect_match(jedna, "90% CI średniej", fixed = TRUE)
  expect_match(jedna, "*N* = 5", fixed = TRUE)
  expect_match(jedna, "odniesienie = 3.00", fixed = TRUE)
  expect_match(jedna, "alpha = 0.010", fixed = TRUE)
  niez <- wniosek_ind(t.test(x, y, mu = 2))
  expect_match(niez, "x minus y = -3.20", fixed = TRUE)
  expect_match(niez, "różnica w H0 = 2.00", fixed = TRUE)
  expect_match(niez, "95% CI różnicy średnich", fixed = TRUE)
  expect_false(grepl("*N*", niez, fixed = TRUE))
  pary <- wniosek_paired(t.test(x, y, paired = TRUE))
  expect_match(pary, "*N* par = 5", fixed = TRUE)
  expect_match(pary, "95% CI średniej różnicy", fixed = TRUE)
  jednostronny <- wniosek_one_sample(t.test(x, mu = 3, alternative = "less"))
  expect_match(jednostronny, "alternatywa jednostronna", fixed = TRUE)
  expect_match(jednostronny, "-Inf", fixed = TRUE)
})

test_that("testy rang nie utożsamiają automatycznie wyniku z medianą", {
  x <- c(1, 4, 8, 13, 19, 26)
  y <- c(2, 6, 11, 17, 24, 32)
  pary <- wniosek_wilcox(wilcox.test(x, y, paired = TRUE, exact = FALSE))
  expect_match(pary, "*V*", fixed = TRUE)
  expect_false(grepl("*W*", pary, fixed = TRUE))
  expect_match(pary, "symetrii", fixed = TRUE)
  niez <- wniosek_mw(wilcox.test(x, y, exact = FALSE))
  expect_match(niez, "*W*", fixed = TRUE)
  expect_match(niez, "dodatkowych założeń", fixed = TRUE)
})

test_that("testy dokładne rozróżniają proporcję i OR", {
  b <- wniosek_fisher(binom.test(26, 40, p = .5))
  expect_match(b, "test dwumianowy", fixed = TRUE)
  expect_match(b, "*N* = 40", fixed = TRUE)
  expect_match(b, "proporcja = 0.65", fixed = TRUE)
  expect_match(b, "95% CI proporcji", fixed = TRUE)
  expect_false(grepl("między zmiennymi", b, fixed = TRUE))
  f <- wniosek_fisher(fisher.test(matrix(c(10, 30, 32, 48), 2, byrow = TRUE)))
  expect_match(f, "test Fishera", fixed = TRUE)
  expect_match(f, "95% CI OR", fixed = TRUE)
})

test_that("chi-kwadrat nie dopisuje df symulacji ani drugiej zmiennej GOF", {
  withr::local_seed(34)
  g <- wniosek_chi2(chisq.test(c(20, 25, 30)))
  expect_match(g, "określon", fixed = TRUE)
  expect_false(grepl("między zmiennymi", g, fixed = TRUE))
  m <- matrix(c(10, 30, 32, 48), 2)
  mc <- wniosek_chi2(chisq.test(m, simulate.p.value = TRUE, B = 99))
  expect_false(grepl("(NA)", mc, fixed = TRUE))
  expect_match(mc, "*N* = 120", fixed = TRUE)
})

test_that("Pearson podaje estymatę r oddzielnie od statystyki t", {
  p <- wniosek_cor(cor.test(1:8, c(1, 3, 2, 5, 4, 7, 8, 6)))
  expect_match(p, "*t*(6)", fixed = TRUE)
  expect_false(grepl("*r*(6)", p, fixed = TRUE))
  expect_match(p, "przyczynowości", fixed = TRUE)
  expect_error(wniosek_anova(aov(mpg ~ factor(cyl) + factor(am), data = mtcars)), "jednoczynnikowy")
  expect_match(wniosek_anova(aov(mpg ~ factor(cyl), data = mtcars)), "ANOVA", fixed = TRUE)
})
