test_that("commit zachowuje bajty CRLF, a stara normalizacja blokuje wysyłkę", {
  k <- tempfile("bajty Git ")
  on.exit({ gc(); unlink(k, recursive = TRUE) }, add = TRUE)
  utworz_projekt("s017", katalog = k)
  gert::git_init(k)
  gert::git_config_set("user.name", "Test kursu", repo = k)
  gert::git_config_set("user.email", "test@example.org", repo = k)
  gert::git_config_set("core.autocrlf", "true", repo = k)
  pliki <- c("kurs.yml", "proba.Rmd")
  writeBin(charToRaw("Pierwszy akapit.\r\nDrugi akapit.\r\n"), file.path(k, "proba.Rmd"))
  gert::git_add(c(pliki, ".gitattributes"), repo = k)
  sha <- gert::git_commit("Pliki bez normalizacji", repo = k)
  if (gert::git_info(repo = k)$shorthand != "main") gert::git_branch_create("main", checkout = TRUE, repo = k)
  h <- badaniaZI:::hashe_plikow(k, pliki)
  expect_true(badaniaZI:::sprawdz_bajty_commitu(k, pliki, h, sha))
  expect_identical(badaniaZI:::hashe_plikow(k, pliki), h)
  badaniaZI:::pisz_linie("* text eol=lf", file.path(k, ".gitattributes"))
  writeBin(charToRaw("Zmieniony akapit.\r\nDrugi akapit.\r\n"), file.path(k, "proba.Rmd"))
  h <- badaniaZI:::hashe_plikow(k, pliki)
  gert::git_add(c(pliki, ".gitattributes"), repo = k)
  sha <- gert::git_commit("Stare reguły końców linii", repo = k)
  expect_error(badaniaZI:::sprawdz_bajty_commitu(k, pliki, h, sha), "Zapis w Git różni")
  expect_identical(badaniaZI:::hashe_plikow(k, pliki), h)
  expect_identical(gert::git_info(repo = k)$commit, sha)
})
