test_that("warianty są odtwarzalne i nie zmieniają strumienia RNG", {
  set.seed(813)
  stan <- .Random.seed
  a <- generuj_dane("s017", "S03")
  expect_identical(.Random.seed, stan)
  expect_identical(a$dane, generuj_dane("s017", "S03")$dane)
  expect_false(identical(a$dane, generuj_dane("s018", "S03")$dane))
  expect_true(a$manifest$syntetyczne)
  expect_match(a$manifest$klucz_wariantu, "^[0-9a-f]{64}$")
  rm(".Random.seed", envir = .GlobalEnv)
  invisible(generuj_dane("s017"))
  expect_false(exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE))
})

test_that("20 scenariuszy pozwala wykonać wspólny rdzeń dla różnych ID i N", {
  expect_identical(scenariusze()$id, sprintf("S%02d", 1:20))
  expect_equal(scenariusz("S04")$grupy[2], "media społecznościowe")
  expect_false(any(grepl("<U+", scenariusze()$tytul, fixed = TRUE)))
  for (s in scenariusze()$id) for (n in c(120L, 150L, 180L)) {
    x <- generuj_dane(paste0("s", n), s, n = n)
    expect_equal(nrow(x$dane), n, info = s)
    expect_length(x$scenariusz$pozycje, 6L)
    y <- przygotuj_ankiete(x$dane)
    d <- y$dane
    expect_equal(nrow(d), n - 2L)
    expect_false(anyDuplicated(d$id_odpowiedzi) > 0)
    expect_equal(y$dziennik$liczba[4L], 2L)
    d$pozycja_3 <- odwroc_pozycje(d$pozycja_3)
    indeks <- indeks_ankiety(d[paste0("pozycja_", 1:6)])
    expect_true(all(is.na(indeks) | (indeks >= 1 & indeks <= 5)))
    expect_true(all(table(d$grupa[!is.na(indeks)]) >= 40), info = s)
    expect_true(all(is.na(d$czas_wyszukiwania) | (d$czas_wyszukiwania >= 0 & d$czas_wyszukiwania <= 120)))
    expect_true(all(is.na(d$czestosc_korzystania) | d$czestosc_korzystania %in% 1:5))
    expect_true(all(d$powodzenie %in% 0:1))
    expect_true(all(vapply(d[paste0("pozycja_", 1:6)], function(z) mean(is.na(z)) >= .02 && mean(is.na(z)) <= .05, logical(1))))
    expect_true(is.finite(stats::sd(indeks, na.rm = TRUE)))
  }
})

test_that("manifest i zapis chronią surową wersję", {
  x <- generuj_dane("s017")
  katalog <- tempfile("dane żółte ")
  on.exit(unlink(katalog, recursive = TRUE))
  zapisz_dane(x, katalog)
  manifest <- jsonlite::read_json(file.path(katalog, "manifest.json"))
  expect_identical(manifest$sha256_csv, digest::digest(file = file.path(katalog, "surowe.csv"), algo = "sha256"))
  bajty <- readBin(file.path(katalog, "surowe.csv"), "raw", n = file.info(file.path(katalog, "surowe.csv"))$size)
  expect_false(as.raw(13) %in% bajty)
  expect_true(as.raw(10) %in% bajty)
  expect_identical(manifest$sha256_rds, digest::digest(file = file.path(katalog, "surowe.rds"), algo = "sha256"))
  expect_identical(manifest$sha256_slownik, digest::digest(file = file.path(katalog, "slownik.csv"), algo = "sha256"))
  expect_identical(manifest$sha256_scenariusz, digest::digest(file = file.path(katalog, "scenariusz.yml"), algo = "sha256"))
  slownik <- utils::read.csv(file.path(katalog, "slownik.csv"), encoding = "UTF-8", stringsAsFactors = FALSE, na.strings = character())
  expect_equal(slownik, x$slownik)
  d <- utils::read.csv(file.path(katalog, "surowe.csv"), encoding = "UTF-8", stringsAsFactors = FALSE)
  expect_equal(d, x$dane)
  expect_error(zapisz_dane(x, katalog), "istnieje")
  x$dane$powodzenie[1L] <- 1L - x$dane$powodzenie[1L]
  expect_error(zapisz_dane(x, tempfile()), "zmieniono")
  expect_error(generuj_dane("s017", n = 119), "120")
  expect_error(generuj_dane("s017", "S21"), "scenariusz")
  expect_error(sprawdz_warianty(c("s017", "s017"), "S01"), "Roster")
  expect_false(anyDuplicated(sprawdz_warianty(sprintf("s%03d", 1:100), "S01")$seed) > 0)
})

test_that("zapisany wariant odczytuje się bez generatora i bez zmiany RNG", {
  k <- tempfile("zapisany wariant ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  x <- generuj_dane("s017", "S11")
  zapisz_dane(x, k)
  set.seed(765)
  stan <- .Random.seed
  testthat::local_mocked_bindings(generuj_dane = function(...) stop("Nie wolno losować"),
                                 scenariusz = function(...) stop("Nie wolno czytać nowej karty"))
  y <- wczytaj_dane(k, id = "s017", scenariusz = "S11", rocznik = "2026-27")
  expect_identical(y$dane, x$dane)
  expect_equal(y$slownik, x$slownik)
  expect_equal(y$scenariusz, x$scenariusz)
  expect_identical(.Random.seed, stan)
  expect_error(wczytaj_dane(k, id = "s999"), "inne id")
  expect_error(wczytaj_dane(k, scenariusz = "S02"), "inne scenariusz")
  plik <- file.path(k, "scenariusz.yml")
  tekst <- readLines(plik, encoding = "UTF-8")
  badaniaZI:::pisz_linie(c(tekst, "# zmiana pliku"), plik)
  expect_error(wczytaj_dane(k), "hash pliku scenariusz.yml")
  expect_identical(tail(readLines(plik, encoding = "UTF-8"), 1L), "# zmiana pliku")
})

test_that("zmienione metadane nie podszywają się pod inne ID", {
  k <- tempfile("manifest-")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  zapisz_dane(generuj_dane("s017", "S02"), k)
  p <- file.path(k, "manifest.json")
  m <- jsonlite::read_json(p, simplifyVector = TRUE)
  m$id <- "s018"
  jsonlite::write_json(m, p, auto_unbox = TRUE)
  expect_error(wczytaj_dane(k, id = "s018"), "Metadane i klucz")
})

test_that("przykład z zainstalowanej paczki zachowuje hashe i polskie etykiety", {
  folder <- badaniaZI:::zasob("extdata", "przyklad")
  m <- jsonlite::read_json(file.path(folder, "manifest.json"))
  expect_identical(m$sha256_csv, digest::digest(file = file.path(folder, "surowe.csv"), algo = "sha256"))
  expect_identical(m$sha256_rds, digest::digest(file = file.path(folder, "surowe.rds"), algo = "sha256"))
  expect_equal(dane_przykladowe(), readRDS(file.path(folder, "surowe.rds")))
  expect_setequal(unique(dane_przykladowe()$grupa), c("nowi", "doświadczeni"))
})
