test_that("puste pola Rmd blokują render bez wymogu liczby słów", {
  k <- tempfile("moje badania ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s017", katalog = k)
  p <- przygotuj_zadanie("Z01", k)
  local_mocked_bindings(renderuj_prace = function(...) stop("NIE URUCHAMIAJ"), .package = "badaniaZI")
  r <- sprawdz_zadanie("Z01", k)
  expect_false(r$ok)
  expect_match(r$kontrole$opis[1L], "S01")
  t <- readLines(p, encoding = "UTF-8")
  for (s in sprintf("S%02d", 1:5)) t <- badaniaZI:::wstaw_odpowiedz(t, s, "Krótki akapit.")
  badaniaZI:::pisz_linie(t, p)
  r <- sprawdz_zadanie("Z01", k, uruchom = FALSE)
  expect_true(r$kontrole$ok[1L])
  expect_false(r$ok)
  expect_match(tail(r$kontrole$opis, 1L), "Brak aktualnego PDF")
})

test_that("adresy z tokenem i ścieżki obcego serwera nie są przyjmowane", {
  expect_equal(badaniaZI:::nazwa_repo("https://github.com/prowadzacy/badania-s017.git"), "prowadzacy/badania-s017")
  expect_error(badaniaZI:::nazwa_repo("https://token@github.com/prowadzacy/badania-s017.git"), "repo_url")
  expect_error(badaniaZI:::nazwa_repo("https://example.org/prowadzacy/badania-s017.git"), "repo_url")
})

test_that("zmieniony skrypt i sekret w odpowiedzi nie są wykonywane ani ujawniane", {
  k <- tempfile("własne R ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s019", katalog = k)
  p <- przygotuj_zadanie("Z01", k)
  t <- readLines(p, encoding = "UTF-8")
  for (s in sprintf("S%02d", 1:5)) t <- badaniaZI:::wstaw_odpowiedz(t, s, "Krótki akapit.")
  badaniaZI:::pisz_linie(t, p)
  local_mocked_bindings(renderuj_prace = function(...) stop("NIE URUCHAMIAJ"), .package = "badaniaZI")
  sekret <- paste0("github_pat_", paste(rep("x", 30), collapse = ""))
  badaniaZI:::pisz_linie(badaniaZI:::wstaw_odpowiedz(t, "S01", sekret), p)
  r <- sprawdz_zadanie("Z01", k)
  expect_false(r$ok)
  expect_match(r$kontrole$opis[1L], "token GitHub")
  expect_false(any(grepl(sekret, r$kontrole$opis, fixed = TRUE)))
  badaniaZI:::pisz_linie(t, p)
  writeLines('stop("NIE WYKONUJ")', file.path(dirname(p), "analiza.R"))
  r <- sprawdz_zadanie("Z01", k)
  expect_false(r$ok)
  expect_false(any(grepl("NIE WYKONUJ|NIE URUCHAMIAJ", r$kontrole$opis)))
})
