zbuduj <- function(p) {
  expect_s3_class(p, "ggplot")
  expect_silent(ggplot2::ggplot_build(p))
}

test_that("wykresy rozkładów budują się dla małych przykładów", {
  x <- c(2, 4, 5, 7, 8, 13, 30)
  zbuduj(wykres_histogram(x, 5, zaznacz = c(5, 10), dopasuj = c("normalny", "lognormalny")))
  zbuduj(wykres_histogram_panele(list(A = x, B = x), c(1, 5), poczatek = 0, srednia = TRUE, odniesienie = 10))
  zbuduj(wykres_czestosci(1:5, c(2, 3, 5, 7, 3)))
  zbuduj(wykres_dystrybuanta(x, prog = 8, dopasuj = c("normalny", "lognormalny")))
  zbuduj(wykres_licznosci_odsetki(c("A", "B"), c(16, 60), c(20, 100)))
  zbuduj(wykres_sd_se(c(x, 3, 9, 11), c(5, 10)))
  zbuduj(wykres_rozklad_dyskretny(0:3, stats::dbinom(0:3, 3, 0.5)))
  zbuduj(wykres_rozklad_dyskretny(0:8, stats::dhyper(0:8, 10, 10, 8), zaznacz = c(0, 1, 7, 8), dystrybuanta = FALSE))
  zbuduj(wykres_gestosc_pole(function(v) stats::dexp(v, 0.1), 0, 40, a = 5, b = 10, linie = 6.93))
  zbuduj(wykres_t_z(c(3, 15)))
  for (r in c("t", "normalny")) zbuduj(wykres_ogony(2, r, 8))
  zbuduj(wykres_ogony(3.36, "chi2", 1))
  zbuduj(wykres_ogony(3.5, "F", c(2, 6)))
  zbuduj(wykres_rozklady_estymatora(c(10, 11.5), c(0.6, 1.6), c("A", "B"), 10))
  zbuduj(wykres_bledy_testu(3, 99))
  zbuduj(wykres_moc(c(0.3, 0.5), seq(10, 100, 10)))
  zbuduj(wykres_wielokrotne_testy(1:20))
  zbuduj(wykres_rozklad_zerowy(c(-2, -1, -1, 0, 0, 0, 1, 1, 2), 1.5, 0.5))
  zbuduj(wykres_bootstrap(stats::qnorm(stats::ppoints(200), 10, 1), 0.25))
})

test_that("wykresy porównań i związków budują się dla małych przykładów", {
  tab <- matrix(c(18, 12, 32, 8), 2, byrow = TRUE, dimnames = list(c("A", "B"), c("Tak", "Nie")))
  zbuduj(wykres_kwantylowy(list(A = c(1, 2, 3, 4, 10), B = 1:8)))
  zbuduj(wykres_chi2(c(1, 2, 4)))
  zbuduj(wykres_pary(c(6, 8, 10), c(5, 6, 9), c("a", "b", "c")))
  zbuduj(wykres_anova(c(4, 5, 6, 7, 8, 9), rep(c("A", "B"), each = 3)))
  zbuduj(wykres_theta(c(8, 10, 12), c(4, 8, 12)))
  zbuduj(wykres_obserwowane_oczekiwane(tab))
  x <- c(1, 2, 2, 3, 4, 5); y <- c(15, 12, 14, 10, 9, 6)
  zbuduj(wykres_pasma_regresji(x, y, x0 = 3, etykiety = letters[1:6]))
  zbuduj(wykres_reszty(list(A = data.frame(x = x, y = y))))
  zbuduj(wykres_kalibracja(c(40, 50, 60), c(20, 30, 40)))
  zbuduj(wykres_galeria_r(c(0, -0.6), n = 50))
  zbuduj(wykres_anscombe())
  zbuduj(wykres_wplyw(x, y, c(9, 14)))
})

test_that("obliczenia wykresów rozkładów dają oczekiwane liczby", {
  d <- badaniaZI:::przedzialy_histogramu(c(2, 4, 5, 7, 8, 13, 30), 5, 0)
  expect_equal(d$n, c(3, 2, 1, 0, 0, 1))
  expect_equal(d$od[1], 0)
  p <- wykres_histogram(c(2, 4, 5, 7, 8, 13, 30), 5, zaznacz = c(5, 10))
  expect_match(p$labels$subtitle, "2 z 7")
  zerowy <- wykres_rozklad_zerowy(c(-2, -1, -1, 0, 0, 0, 1, 1, 2), 1, 0.5, poczatek = -2.25, dokladny = TRUE)
  expect_match(zerowy$labels$subtitle, "p = 6/9")
  theta <- wykres_theta(c(8, 10, 12, 14, 16), c(4, 6, 8, 10, 12))
  expect_match(theta$labels$subtitle, "0,82")
  galeria <- ggplot2::ggplot_build(wykres_galeria_r(-0.6, n = 100))$data[[1]]
  expect_equal(stats::cor(galeria$x, galeria$y), -0.6, tolerance = 1e-8)
  expect_error(wykres_rozklad_dyskretny(0:1, c(0.2, 0.2)))
  expect_error(wykres_licznosci_odsetki("A", 5, 4))
})
