test_that("C10 wymaga wariantu C09, a później nie losuje go ponownie", {
  k <- tempfile("zapis projektu żółty ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s017", katalog = k)
  przygotuj_zadanie("Z09", k)
  expect_error(przygotuj_zadanie("Z10", k), "zapisu wariantu")
  expect_false(dir.exists(file.path(k, "zadania/z10")))
  x <- wariant_projektu("Z09", "S05", katalog = k)
  expect_identical(x$manifest$scenariusz, "S05")
  testthat::local_mocked_bindings(generuj_dane = function(...) stop("Drugie losowanie"),
                                 scenariusz = function(...) stop("Bieżący katalog"))
  set.seed(17)
  rng <- .Random.seed
  ponownie <- wariant_projektu("Z09", "S05", id_studenta = "s017", katalog = k)
  expect_identical(ponownie, x)
  przygotuj_zadanie("Z10", k)
  y <- wariant_projektu("Z10", katalog = k)
  expect_identical(y, x)
  expect_identical(.Random.seed, rng)
  expect_error(wariant_projektu("Z09", "S02", katalog = k), "inne scenariusz")
  expect_error(wariant_projektu("Z10", id_studenta = "s999", katalog = k), "ID sesji")
  expect_identical(wariant_projektu("Z10", katalog = k), x)
})

test_that("render nie rozpoczyna wariantu i brak danych nie wywołuje naprawy", {
  k <- tempfile("bez losowania ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s017", katalog = k)
  przygotuj_zadanie("Z09", k)
  opcje <- options(knitr.in.progress = TRUE)
  on.exit(options(opcje), add = TRUE)
  expect_error(wariant_projektu("Z09", "S02", katalog = k), "pierwszy chunk")
  expect_false(dir.exists(file.path(k, "zadania/z09/dane")))
  options(knitr.in.progress = FALSE)
  x <- wariant_projektu("Z09", "S02", katalog = k)
  testthat::local_mocked_bindings(generuj_dane = function(...) stop("Nie regeneruj"))
  dane <- file.path(k, "zadania/z09/dane")
  expect_true(file.rename(dane, paste0(dane, "-kopia")))
  expect_error(wariant_projektu("Z09", "S02", katalog = k), "pełnego zapisu")
  expect_false(dir.exists(dane))
  expect_true(file.exists(file.path(k, "zadania/z09/wariant.yml")))
  expect_true(file.rename(paste0(dane, "-kopia"), dane))
  expect_identical(wariant_projektu("Z09", "S02", katalog = k), x)
})

test_that("raport kopiuje własne akapity raz i zachowuje późniejsze poprawki", {
  k <- tempfile("raport z odpowiedzi ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s018", katalog = k)
  przygotuj_zadanie("Z09", k)
  wariant_projektu("Z09", "S05", katalog = k)
  przygotuj_zadanie("Z10", k)
  wlasne <- list()
  for (z in c("Z09", "Z10")) {
    p <- file.path(k, "zadania", tolower(z), "zadanie.Rmd")
    tekst <- readLines(p, encoding = "UTF-8")
    for (i in 1:5) {
      pole <- sprintf("S%02d", i)
      akapit <- c(paste(z, pole, "— własny tekst: żółć, 95% CI i p."), "",
                  "Drugie zdanie z **własnym wyróżnieniem**, nie interpretacja funkcji.")
      wlasne[[paste(z, pole)]] <- akapit
      tekst <- badaniaZI:::wstaw_odpowiedz(tekst, pole, akapit)
    }
    badaniaZI:::pisz_linie(tekst, p)
  }
  testthat::local_mocked_bindings(generuj_dane = function(...) stop("Nie generuj raportu z nowych danych"))
  p <- przygotuj_raport(k)
  tekst <- readLines(p, encoding = "UTF-8")
  pola <- badaniaZI:::odczytaj_odpowiedzi(tekst, sprintf("P%02d", 1:11))
  mapa <- badaniaZI:::czytaj_yaml(badaniaZI:::zasob("szablony/projekt/przeniesienie.yml"))
  for (w in mapa$odpowiedzi) expect_identical(pola[[w$pole]], wlasne[[paste(w$zadanie, w$odpowiedz)]])
  expect_identical(pola$P11, "[UZUPELNIJ_P11]")
  expect_false(any(grepl("{{", tekst, fixed = TRUE)))
  expect_identical(badaniaZI:::naglowek_rmd(tekst)$params$scenariusz, "S05")
  tekst <- badaniaZI:::wstaw_odpowiedz(tekst, "P01", "Poprawiony tekst tylko w raporcie.")
  badaniaZI:::pisz_linie(tekst, p)
  hash <- digest::digest(file = p)
  data <- file.info(p)$mtime
  # Późniejsza redakcja Z09 nie może nadpisać już utworzonego raportu.
  z09 <- file.path(k, "zadania/z09/zadanie.Rmd")
  ztekst <- badaniaZI:::wstaw_odpowiedz(readLines(z09, encoding = "UTF-8"), "S01", "Późniejsza zmiana Z09.")
  badaniaZI:::pisz_linie(ztekst, z09)
  expect_identical(przygotuj_raport(k), p)
  expect_identical(digest::digest(file = p), hash)
  expect_identical(file.info(p)$mtime, data)
  expect_identical(wczytaj_dane(file.path(dirname(p), "dane"))$dane,
                   wariant_projektu("Z10", katalog = k)$dane)
})

test_that("puste pola pozostają do uzupełnienia; wadliwe znaczniki nie są zgadywane", {
  k <- tempfile("pola raportu ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s017", katalog = k)
  przygotuj_zadanie("Z09", k)
  wariant_projektu("Z09", "S02", katalog = k)
  przygotuj_zadanie("Z10", k)
  p <- przygotuj_raport(k)
  t <- readLines(p, encoding = "UTF-8")
  expect_equal(sum(grepl("^\\[UZUPELNIJ_P", t)), 11L)
  kod <- c("```r", "<!-- odpowiedz:S01 -->", "x <- 1", "<!-- /odpowiedz:S01 -->", "```")
  expect_error(badaniaZI:::odczytaj_odpowiedzi(kod, "S01"), "poza kodem")
  a <- c("<!-- odpowiedz:S01 -->", "Akapit.", "<!-- /odpowiedz:S01 -->")
  expect_error(badaniaZI:::odczytaj_odpowiedzi(c(a, a), "S01"), "jedną parę")
  expect_error(badaniaZI:::odczytaj_odpowiedzi(c("```r", a), "S01"), "niezamknięty")
  n <- c("<!-- odpowiedz:S01 -->", "<!-- odpowiedz:S02 -->", "<!-- /odpowiedz:S01 -->", "<!-- /odpowiedz:S02 -->")
  expect_error(badaniaZI:::odczytaj_odpowiedzi(n, c("S01", "S02")), "nakładają")
})

test_that("lokalny commit i clone zachowują hashe wariantu oraz helperów", {
  k <- tempfile("wariant git ")
  kopia <- tempfile("odtworzenie git ")
  on.exit({ gc(); unlink(c(k, kopia), recursive = TRUE) }, add = TRUE)
  utworz_projekt("s017", katalog = k)
  przygotuj_zadanie("Z09", k)
  wariant_projektu("Z09", "S11", katalog = k)
  przygotuj_zadanie("Z10", k)
  przygotuj_raport(k)
  pliki <- list.files(k, recursive = TRUE, all.files = TRUE, no.. = TRUE)
  gert::git_init(k)
  gert::git_config_set("user.name", "Test wariantu", repo = k)
  gert::git_config_set("user.email", "test@example.org", repo = k)
  gert::git_config_set("core.autocrlf", "true", repo = k)
  gert::git_add(pliki, repo = k)
  gert::git_commit("Zapis testowej pracy", repo = k)
  gert::git_clone(k, kopia, verbose = FALSE)
  expect_identical(wariant_projektu("Z10", katalog = kopia),
                   wariant_projektu("Z09", katalog = k))
  expect_true(file.exists(przygotuj_zadanie("Z09", kopia)))
  expect_true(file.exists(przygotuj_zadanie("Z10", kopia)))
  expect_true(file.exists(przygotuj_raport(kopia)))
})
