test_that("każde zadanie ma cały LEARN/CHALLENGE i ID w jednym Rmd", {
  k <- tempfile("Rmd ćwiczenia ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s017", katalog = k)
  for (nr in 1:10) {
    id <- sprintf("Z%02d", nr)
    if (nr == 10L) wariant_projektu("Z09", "S02", katalog = k)
    plik <- przygotuj_zadanie(id, k)
    expect_identical(basename(plik), "zadanie.Rmd")
    expect_true(file.exists(plik))
    tekst <- readLines(plik, encoding = "UTF-8")
    naglowek <- badaniaZI:::naglowek_rmd(tekst)
    expect_identical(naglowek$author, "ID: s017")
    expect_identical(naglowek$params$id_studenta, "s017")
    expect_equal(sum(grepl("^# LEARN [1-5]:", tekst)), 5L)
    expect_equal(sum(grepl("^## CHALLENGE [1-5]:", tekst)), 5L)
    expect_equal(sum(grepl("^<!-- odpowiedz:S0[1-5] -->$", tekst)), 5L)
    expect_equal(sum(grepl("^\\[UZUPELNIJ_S0[1-5]\\]$", tekst)), 5L)
    expect_true(any(grepl("zaloguj_github()", tekst, fixed = TRUE)))
    expect_true(any(grepl(sprintf('"C%02d", id_studenta = ID', nr), tekst, fixed = TRUE)))
    helper <- file.path(dirname(plik), "analiza.R")
    wzorzec <- badaniaZI:::zasob("materialy", sprintf("c%02d", nr), "analiza.R")
    expect_identical(digest::digest(file = helper), digest::digest(file = wzorzec))
    expect_false(file.exists(file.path(dirname(plik), "odpowiedzi.md")))
    expect_false(dir.exists(file.path(k, "dane")))
    bajty <- readBin(plik, "raw", n = file.info(plik)$size)
    expect_false(as.raw(13) %in% bajty)
  }
})

test_that("ponowne przygotowanie zachowuje odpowiedzi i ich datę zapisu", {
  k <- tempfile("Rmd własne ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s018", katalog = k)
  p <- przygotuj_zadanie("Z02", k)
  tekst <- readLines(p, encoding = "UTF-8")
  tekst <- gsub("[UZUPELNIJ_S01]", "Własny krótki akapit: 0 oznacza nie, nie brak.", tekst, fixed = TRUE)
  badaniaZI:::pisz_linie(tekst, p)
  hash <- digest::digest(file = p)
  data <- file.info(p)$mtime
  expect_identical(przygotuj_zadanie("Z02", k), p)
  expect_identical(digest::digest(file = p), hash)
  expect_identical(file.info(p)$mtime, data)
  plik_cfg <- file.path(k, "kurs.yml")
  cfg <- badaniaZI:::czytaj_yaml(plik_cfg)
  cfg$id <- "s019"
  yaml::write_yaml(cfg, plik_cfg)
  expect_error(przygotuj_zadanie("Z02", k), "ID")
  expect_identical(digest::digest(file = p), hash)
})

test_that("stary lub uszkodzony katalog nie jest cicho nadpisywany", {
  k <- tempfile("Rmd bez nadpisania ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s017", katalog = k)
  folder <- file.path(k, "zadania", "z01")
  dir.create(folder, recursive = TRUE)
  stary <- file.path(folder, "odpowiedzi.md")
  writeLines("Moja wcześniejsza odpowiedź.", stary, useBytes = TRUE)
  hash <- digest::digest(file = stary)
  expect_error(przygotuj_zadanie("Z01", k), "migracji")
  expect_identical(digest::digest(file = stary), hash)
  expect_false(file.exists(file.path(folder, "zadanie.Rmd")))
  p <- przygotuj_zadanie("Z02", k)
  helper <- file.path(dirname(p), "analiza.R")
  writeLines("zmieniony <- TRUE", helper)
  expect_error(przygotuj_zadanie("Z02", k), "analiza.R różni")
  expect_identical(readLines(helper), "zmieniony <- TRUE")
  expect_error(badaniaZI:::sciezka_pracy(k, "../inne"), "wewnątrz")
  expect_error(badaniaZI:::sciezka_pracy(k, "C:/inne"), "wewnątrz")
})
