test_that("nowe API przygotowuje dokładne wejścia do wszystkich prac", {
  k <- tempfile("wejścia Rmd ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s017", katalog = k)
  for (id in sprintf("Z%02d", 1:10)) {
    p <- przygotuj_zadanie(id, k)
    if (id == "Z09") wariant_projektu("Z09", "S02", katalog = k)
    tekst <- readLines(p, encoding = "UTF-8")
    for (pole in badaniaZI:::pola_pracy(id)) tekst <- badaniaZI:::wstaw_odpowiedz(tekst, pole,
      "Własny krótki akapit o syntetycznym wyniku i jego ograniczeniu.")
    badaniaZI:::pisz_linie(tekst, p)
    x <- badaniaZI:::kontroluj_wejscia_rmd(id, k)
    expect_identical(x$id, id)
    expect_identical(names(x$hashe), x$pliki)
    expect_length(x$pliki, if (id %in% c("Z09", "Z10")) 11L else 5L)
    expect_false(any(grepl("wspolne/literatura", tekst, fixed = TRUE)))
    expect_true(file.exists(file.path(dirname(p), "literatura.md")))
    writeLines("Ten plik nie należy do oddania.", file.path(dirname(p), "prywatna-notatka.txt"))
    expect_identical(badaniaZI:::kontroluj_wejscia_rmd(id, k)$pliki, x$pliki)
  }
  p <- przygotuj_raport(k)
  tekst <- badaniaZI:::wstaw_odpowiedz(readLines(p, encoding = "UTF-8"), "P11", "Bibliografia: materiały kursu.")
  badaniaZI:::pisz_linie(tekst, p)
  expect_length(badaniaZI:::kontroluj_wejscia_rmd("PROJEKT", k)$pliki, 11L)
})

test_that("preflight odrzuca fałszywy helper nawet ze zmienionym hashem", {
  k <- tempfile("kontrola helpera ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s017", katalog = k)
  p <- przygotuj_zadanie("Z01", k)
  helper <- file.path(dirname(p), "analiza.R")
  writeLines('stop("Nie wykonuj tego helpera")', helper)
  meta_path <- file.path(dirname(p), "zadanie.yml")
  meta <- badaniaZI:::czytaj_yaml(meta_path)
  meta$sha256_analiza <- digest::digest(file = helper, algo = "sha256")
  badaniaZI:::pisz_linie(yaml::as.yaml(meta), meta_path)
  expect_error(badaniaZI:::kontroluj_wejscia_rmd("Z01", k), "innej wersji")
})

test_that("zapisane dane i kod C09 muszą wskazywać ten sam scenariusz", {
  k <- tempfile("kontrola wyboru ")
  on.exit(unlink(k, recursive = TRUE), add = TRUE)
  utworz_projekt("s017", katalog = k)
  p <- przygotuj_zadanie("Z09", k)
  wariant_projektu("Z09", "S05", katalog = k)
  tekst <- readLines(p, encoding = "UTF-8")
  for (pole in badaniaZI:::pola_pracy("Z09")) tekst <- badaniaZI:::wstaw_odpowiedz(tekst, pole, "Własny plan badania.")
  badaniaZI:::pisz_linie(tekst, p)
  expect_error(badaniaZI:::kontroluj_wejscia_rmd("Z09", k), "Scenariusz w chunku")
  i <- grep('^projekt <- przygotuj_wariant_projektu', tekst)
  tekst[i] <- sub("S02", "S05", tekst[i], fixed = TRUE)
  badaniaZI:::pisz_linie(tekst, p)
  expect_identical(badaniaZI:::kontroluj_wejscia_rmd("Z09", k)$id, "Z09")
})
